export const GAME_WIDTH = 480
export const GAME_HEIGHT = 720
export const PLAYER_SPEED = 360
export const PLAYER_SLOW_SPEED = 168
export const PLAYER_BULLET_SPEED = 720
export const PLAYER_FIRE_MS = 130
export const PLAYER_HITBOX_WIDTH = 16
export const PLAYER_HITBOX_HEIGHT = 16
export const MAX_WEAPON_LEVEL = 3
export const MAX_BOMBS = 2
export const POWER_UP_SPEED = 92
export const POWER_UP_DRIFT_SPEED = 88
export const POWER_UP_LIFETIME_MS = 8_000
export const POWER_UP_TURN_MS = 780
export const PLAYER_HIT_INVULNERABLE_MS = 1_100
export const PLAYER_BOMB_INVULNERABLE_MS = 1_350
export const PLAYER_GRAZE_RADIUS = 34
export const PLAYER_JET_KEY = 'player-jet'
export const PLAYER_JET_ASSET = '/assets/combatjet-highres.png'
export const UI_FONT = 'system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif'
export const MONO_FONT = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace'
export const DEBUG_HITBOXES = import.meta.env.DEV
export const SETTINGS_STORAGE_KEY = 'space-shooter-demo-settings-v1'
export const BEST_SCORE_PREFIX = 'space-shooter-demo-best-v1'
