export const GAME_FEEL = {
  depths: {
    projectileTrail: 17,
    projectileLaunch: 25,
    impact: 34,
    screenFlash: 58,
    screenDim: 57,
  },
  audio: {
    parrySuccessKey: 'parry_success',
    parrySuccessVolume: 0.72,
  },
  parry: {
    hitStopMs: 80,
    cameraShakeMs: 120,
    cameraShakeIntensity: 0.0055,
    screenFlashMs: 80,
    screenFlashAlpha: 0.58,
    shockwaveStartRadius: 12,
    shockwaveEndScale: 7.4,
    shockwaveMs: 220,
    particleMin: 8,
    particleMax: 12,
    particleMinDistance: 24,
    particleMaxDistance: 62,
    particleMinMs: 180,
    particleMaxMs: 340,
    bulletFlashMs: 92,
    bulletFlashScale: 1.34,
  },
  perfectParry: {
    dimMs: 100,
    dimFadeMs: 90,
    dimAlpha: 0.52,
    launchSlashLength: 150,
    launchSlashWidth: 12,
    launchFlashMs: 180,
  },
  counterShot: {
    reflectTrailIntervalMs: 58,
    waveTrailIntervalMs: 34,
    reflectTrailMs: 140,
    waveTrailMs: 230,
    reflectTrailAlpha: 0.28,
    waveTrailAlpha: 0.42,
    launchRingMs: 180,
    launchRingScale: 2.6,
  },
  bossHit: {
    blinkMs: 100,
    blinkAlpha: 0.86,
    cameraShakeMs: 90,
    cameraShakeIntensity: 0.0028,
    waveCameraShakeMs: 110,
    waveCameraShakeIntensity: 0.0038,
  },
} as const
